# Generated by Django 4.2.10 on 2024-03-07 08:34

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_measurement.models
import djmoney.models.fields
import measurement.measures.mass
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_pt', models.CharField(max_length=255)),
                ('telp', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('terms_of_payment', models.CharField(max_length=10)),
                ('pengiriman', models.CharField(max_length=50)),
                ('npwp', models.CharField(max_length=255)),
                ('faktur', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('SKU', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('Tanggal', models.DateField(default=django.utils.timezone.now)),
                ('nama', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=10)),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('CNY', 'Chinese Yuan (CNY)'), ('IDR', 'Indonesian Rupiah (IDR)'), ('TWD', 'New Taiwan Dollar (TWD)'), ('SGD', 'Singapore Dollar (SGD)'), ('USD', 'US Dollar (USD)')], default='IDR', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='IDR', max_digits=15)),
                ('gambar', models.ImageField(upload_to='')),
                ('is_approved', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page1.category')),
            ],
        ),
        migrations.CreateModel(
            name='Messenger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#3a87ad', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_pt', models.CharField(max_length=255)),
                ('telp', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('terms_of_payment', models.CharField(max_length=10)),
                ('npwp', models.CharField(max_length=255)),
                ('faktur', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('jenis', models.CharField(max_length=20)),
                ('nomor_plat', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_PO_currency', djmoney.models.fields.CurrencyField(choices=[('CNY', 'Chinese Yuan (CNY)'), ('IDR', 'Indonesian Rupiah (IDR)'), ('TWD', 'New Taiwan Dollar (TWD)'), ('SGD', 'Singapore Dollar (SGD)'), ('USD', 'US Dollar (USD)')], default='IDR', editable=False, max_length=3, null=True)),
                ('revenue_PO', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='IDR', max_digits=15, null=True)),
                ('nomor_PO', models.IntegerField(blank=True, null=True)),
                ('tanggal_PO', models.DateField(blank=True, null=True)),
                ('tanggal_process', models.DateField(blank=True, null=True)),
                ('tanggal_input_accurate', models.DateField(blank=True, null=True)),
                ('tanggal_pengiriman_barang', models.DateField(blank=True, null=True)),
                ('tanggal_pengiriman_invoice', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('order', 'Order Created'), ('pending', 'Pending'), ('process', 'Process'), ('accurate', 'Accurate'), ('pengiriman', 'Pengiriman Barang'), ('invoice', 'Pengiriman Invoice'), ('complete', 'Completed')], max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page1.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page1.items')),
            ],
        ),
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('payload', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SupplierPIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telp', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Role', models.CharField(max_length=50)),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page1.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierAlamat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('penagihan', 'Alamat Penagihan'), ('pengiriman', 'Alamat Pengiriman')], max_length=15)),
                ('provinsi', models.CharField(max_length=255)),
                ('kota', models.CharField(max_length=50)),
                ('kecamatan', models.CharField(max_length=50)),
                ('kelurahan', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=50)),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page1.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_PO_currency', djmoney.models.fields.CurrencyField(choices=[('CNY', 'Chinese Yuan (CNY)'), ('IDR', 'Indonesian Rupiah (IDR)'), ('TWD', 'New Taiwan Dollar (TWD)'), ('SGD', 'Singapore Dollar (SGD)'), ('USD', 'US Dollar (USD)')], default='IDR', editable=False, max_length=3, null=True)),
                ('revenue_PO', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='IDR', max_digits=15, null=True)),
                ('nomor_PO', models.IntegerField(blank=True, null=True)),
                ('tanggal_PO', models.DateField(blank=True, null=True)),
                ('tanggal_process', models.DateField(blank=True, null=True)),
                ('tanggal_input_accurate', models.DateField(blank=True, null=True)),
                ('tanggal_pengiriman_barang', models.DateField(blank=True, null=True)),
                ('tanggal_pengiriman_invoice', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('order', 'Order Created'), ('pending', 'Pending'), ('process', 'Process'), ('accurate', 'Accurate'), ('pengiriman', 'Pengiriman Barang'), ('invoice', 'Pengiriman Invoice'), ('complete', 'Completed')], max_length=30)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page1.items')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page1.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_sumber', models.CharField(choices=[('Online Store', 'Online Store'), ('Rabrik', 'Pabrik'), ('Reseller', 'Reseller'), ('Grosir', 'Grosir')], max_length=30)),
                ('nama_perusahaan', models.CharField(max_length=255)),
                ('telp', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page1.items')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('start_location', models.CharField(max_length=255, null=True)),
                ('destination', models.CharField(max_length=255, null=True)),
                ('package_name', models.CharField(max_length=100, null=True)),
                ('package_dimensions', models.CharField(max_length=100, null=True)),
                ('package_mass', django_measurement.models.MeasurementField(measurement=measurement.measures.mass.Mass, null=True)),
                ('messenger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='page1.messenger')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='page1.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telp', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Role', models.CharField(max_length=50)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page1.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAlamat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('penagihan', 'Alamat Penagihan'), ('pengiriman', 'Alamat Pengiriman')], max_length=15)),
                ('provinsi', models.CharField(max_length=255)),
                ('kota', models.CharField(max_length=50)),
                ('kecamatan', models.CharField(max_length=50)),
                ('kelurahan', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=50)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page1.customer')),
            ],
        ),
    ]
