# Generated by Django 5.0.2 on 2024-02-26 08:40

import django.db.models.deletion
import djmoney.models.fields
import page1.models
import phonenumber_field.modelfields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_pt', models.CharField(max_length=255)),
                ('telp', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('terms_of_payment', models.CharField(max_length=10)),
                ('pengiriman', models.CharField(max_length=50)),
                ('npwp', models.CharField(max_length=255)),
                ('faktur', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('SKU', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('ATK', 'Alat Tulis Kantor'), ('ELK', 'Elektronik Supplies'), ('FAS', 'Fashion'), ('ITS', 'IT Supplies'), ('KES', 'Kesehatan'), ('LPU', 'Lampu'), ('MAK', 'Makanan'), ('MGF', 'Management Fee'), ('MIN', 'Minuman'), ('MRO', 'Maintenance, Repair, and Operations'), ('OTO', 'Otomotif'), ('PER', 'Peralatan'), ('PRK', 'Perawatan dan Kecantikan'), ('PRT', 'Peralatan Rumah Tangga'), ('RTL', 'Rental'), ('SFT', 'Safety'), ('STG', 'Storage'), ('TVL', 'Travel'), ('UMM', 'Umum')], max_length=255)),
                ('quantity', models.IntegerField()),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('IDR', 'Indonesian Rupiah (Rp.)'), ('USD', 'US Dollar ($)')], default='IDR', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='IDR', max_digits=15)),
                ('gambar', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_pt', models.CharField(max_length=255)),
                ('telp', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('terms_of_payment', models.CharField(max_length=10)),
                ('npwp', models.CharField(max_length=255)),
                ('faktur', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAlamat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('penagihan', 'Alamat Penagihan'), ('pengiriman', 'Alamat Pengiriman')], max_length=15)),
                ('provinsi', models.CharField(max_length=255)),
                ('kota', models.CharField(max_length=50)),
                ('kecamatan', models.CharField(max_length=50)),
                ('kelurahan', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=50)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page1.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telp', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Role', models.CharField(max_length=50)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page1.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_sumber', models.CharField(choices=[('online', 'Online Store'), ('pabrik', 'Pabrik')], max_length=30)),
                ('nama_perusahaan', models.CharField(max_length=255)),
                ('telp', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page1.items')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_PO_currency', djmoney.models.fields.CurrencyField(choices=[('IDR', 'Indonesian Rupiah (Rp.)'), ('USD', 'US Dollar ($)')], default='IDR', editable=False, max_length=3, null=True)),
                ('revenue_PO', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='IDR', max_digits=15, null=True)),
                ('nomor_PO', models.IntegerField(blank=True, default=0, null=True)),
                ('tanggal_PO', models.DateField(blank=True, default=page1.models.default_date, null=True)),
                ('tanggal_process', models.DateField(blank=True, default=page1.models.default_date, null=True)),
                ('tanggal_input_accurate', models.DateField(blank=True, default=page1.models.default_date, null=True)),
                ('tanggal_pengiriman_barang', models.DateField(blank=True, default=page1.models.default_date, null=True)),
                ('tanggal_pengiriman_invoice', models.DateField(blank=True, default=page1.models.default_date, null=True)),
                ('status', models.CharField(choices=[('order', 'Order Created'), ('pending', 'Pending'), ('process', 'Process'), ('accurate', 'Accurate'), ('pengiriman', 'Pengiriman Barang'), ('invoice', 'Pengiriman Invoice'), ('complete', 'Completed')], max_length=30)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page1.items')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page1.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierAlamat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('penagihan', 'Alamat Penagihan'), ('pengiriman', 'Alamat Pengiriman')], max_length=15)),
                ('provinsi', models.CharField(max_length=255)),
                ('kota', models.CharField(max_length=50)),
                ('kecamatan', models.CharField(max_length=50)),
                ('kelurahan', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=50)),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page1.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierPIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telp', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Role', models.CharField(max_length=50)),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page1.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('payload', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_PO_currency', djmoney.models.fields.CurrencyField(choices=[('IDR', 'Indonesian Rupiah (Rp.)'), ('USD', 'US Dollar ($)')], default='IDR', editable=False, max_length=3, null=True)),
                ('revenue_PO', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='IDR', max_digits=15, null=True)),
                ('nomor_PO', models.IntegerField(blank=True, default=0, null=True)),
                ('tanggal_PO', models.DateField(blank=True, default=page1.models.default_date, null=True)),
                ('tanggal_process', models.DateField(blank=True, default=page1.models.default_date, null=True)),
                ('tanggal_input_accurate', models.DateField(blank=True, default=page1.models.default_date, null=True)),
                ('tanggal_pengiriman_barang', models.DateField(blank=True, default=page1.models.default_date, null=True)),
                ('tanggal_pengiriman_invoice', models.DateField(blank=True, default=page1.models.default_date, null=True)),
                ('status', models.CharField(choices=[('order', 'Order Created'), ('pending', 'Pending'), ('process', 'Process'), ('accurate', 'Accurate'), ('pengiriman', 'Pengiriman Barang'), ('invoice', 'Pengiriman Invoice'), ('complete', 'Completed')], max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page1.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page1.items')),
            ],
        ),
    ]
