# Generated by Django 4.2.10 on 2024-03-07 09:27

from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='IDR', max_digits=15, validators=[djmoney.models.validators.MinMoneyValidator(0)]),
        ),
    ]
