# Generated by Django 4.2.10 on 2024-03-07 09:29

from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0002_alter_items_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='revenue_PO',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='IDR', max_digits=15, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)]),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='revenue_PO',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='IDR', max_digits=15, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)]),
        ),
    ]
