# Generated by Django 5.0.2 on 2024-02-26 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
