# Generated by Django 5.0.2 on 2024-02-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0002_category_alter_items_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
