# Generated by Django 4.2.10 on 2024-03-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0003_alter_purchaseorder_revenue_po_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='nomor_PO',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='nomor_PO',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
