# Generated by Django 5.0.2 on 2024-02-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0003_alter_mymodel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_pt', models.CharField(max_length=255)),
                ('alamat_penagihan', models.CharField(max_length=255)),
                ('alamat_pengiriman', models.CharField(max_length=255)),
                ('telp', models.IntegerField()),
                ('terms_of_payment', models.IntegerField()),
                ('pengiriman', models.BooleanField()),
                ('npwp', models.CharField(max_length=255)),
                ('faktur', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
