# Generated by Django 4.2.10 on 2024-03-08 02:50

from django.db import migrations, models
import django_measurement.models
import djmoney.models.validators
import measurement.measures.mass


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0004_alter_purchaseorder_nomor_po_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='package_mass',
            field=django_measurement.models.MeasurementField(measurement=measurement.measures.mass.Mass, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)]),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='nomor_PO',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='nomor_PO',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
