# Generated by Django 5.0.2 on 2024-02-27 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0003_events_remove_deliveryorder_delivery_person_and_more'),
        ('page1', '0004_alter_items_category'),
    ]

    operations = [
    ]
