# Generated by Django 5.0.2 on 2024-02-16 02:44

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0005_pic_supplier_alter_customer_pengiriman_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='telp',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='pic',
            name='telp',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='telp',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
