# Generated by Django 5.0.2 on 2024-02-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0006_alter_customer_telp_alter_pic_telp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('SKU', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('gambar', models.ImageField(upload_to='')),
                ('sumber', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='pengiriman',
        ),
    ]
