# Generated by Django 4.2.10 on 2024-03-08 03:08

from django.db import migrations
import django_measurement.models
import djmoney.models.validators
import measurement.measures.mass


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0006_alter_events_package_mass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='package_mass',
            field=django_measurement.models.MeasurementField(measurement=measurement.measures.mass.Mass, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)]),
        ),
    ]
