# Generated by Django 4.2.10 on 2024-03-08 04:08

import django.core.validators
from django.db import migrations
import django_measurement.models
import measurement.measures.mass


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0008_alter_events_package_mass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='package_mass',
            field=django_measurement.models.MeasurementField(measurement=measurement.measures.mass.Mass, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
