# Generated by Django 5.0.2 on 2024-02-20 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0010_customeralamat_supplieralamat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplieralamat',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='supplieralamat',
            name='supplier_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='page1.supplier'),
            preserve_default=False,
        ),
    ]
