# Generated by Django 4.2.10 on 2024-03-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0011_alter_items_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='faktur',
        ),
        migrations.AlterField(
            model_name='customer',
            name='terms_of_payment',
            field=models.CharField(max_length=15),
        ),
    ]
