# Generated by Django 4.2.10 on 2024-03-13 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0012_remove_customer_faktur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='messenger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='page1.messenger'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='jenis',
            field=models.CharField(choices=[('truck', 'Truck'), ('mobil', 'Mobil'), ('motor', 'Motor'), ('ojek_online', 'Ojek Online')], max_length=20),
        ),
    ]
