# Generated by Django 5.0.2 on 2024-02-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0013_remove_items_gambar_resized'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='gambar_resized',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
