# Generated by Django 4.2.10 on 2024-03-13 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0013_vehicle_messenger_alter_vehicle_jenis'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinsi', models.CharField(max_length=255)),
                ('kota', models.CharField(max_length=50)),
                ('kecamatan', models.CharField(max_length=50)),
                ('kelurahan', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='catatan',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='upload_type',
            field=models.CharField(default='manual', max_length=10),
        ),
        migrations.AlterField(
            model_name='items',
            name='gambar',
            field=models.ImageField(max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='events',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_destination', to='page1.deliveryaddresses'),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_start_location', to='page1.deliveryaddresses'),
        ),
    ]
