# Generated by Django 4.2.10 on 2024-03-14 07:49

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0014_deliveryaddresses_items_catatan_items_upload_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('instansi_asal', models.CharField(max_length=255, null=True)),
                ('nama', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('tujuan', models.CharField(choices=[('meeting', 'Meeting'), ('survey', 'Survey'), ('interview', 'Interview'), ('lainnya', 'Lainnya')], max_length=20, null=True)),
                ('tujuan_lainnya', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_dikunjungi', models.CharField(max_length=50, null=True)),
                ('tipe', models.CharField(choices=[('unscheduled', 'Unscheduled'), ('scheduled', 'Scheduled')], max_length=15)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('telp', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
    ]
