# Generated by Django 5.0.2 on 2024-02-20 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0015_remove_items_gambar_resized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='alamat_penagihan',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='alamat_pengiriman',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='alamat_penagihan',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='alamat_pengiriman',
        ),
    ]
