# Generated by Django 4.2.10 on 2024-03-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0016_remove_supplier_faktur_supplier_pengiriman_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='pengiriman',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
