# Generated by Django 4.2.10 on 2024-03-25 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0017_alter_supplier_pengiriman'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='customeralamat',
            options={'verbose_name': 'Customer Address', 'verbose_name_plural': 'Customer Addresses'},
        ),
        migrations.AlterModelOptions(
            name='customerpic',
            options={'verbose_name': 'Customer PIC', 'verbose_name_plural': 'Customer PICs'},
        ),
        migrations.AlterModelOptions(
            name='deliveryaddresses',
            options={'verbose_name': 'Delivery Address', 'verbose_name_plural': 'Delivery Addresses'},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Delivery Order', 'verbose_name_plural': 'Delivery Orders'},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='itemsumber',
            options={'verbose_name': 'Item Sumber', 'verbose_name_plural': 'Items Sources'},
        ),
        migrations.AlterModelOptions(
            name='logbook',
            options={'verbose_name': 'Log Book', 'verbose_name_plural': 'Log Books'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'verbose_name': 'Purchase Order', 'verbose_name_plural': 'Purchase Orders'},
        ),
        migrations.AlterModelOptions(
            name='supplieralamat',
            options={'verbose_name': 'Supplier Address', 'verbose_name_plural': 'Supplier Addresses'},
        ),
        migrations.AlterModelOptions(
            name='supplierpic',
            options={'verbose_name': 'Supplier PIC', 'verbose_name_plural': 'Supplier PICs'},
        ),
        migrations.AlterModelOptions(
            name='useractionlog',
            options={'verbose_name': 'User Action Log', 'verbose_name_plural': 'User Action Logs'},
        ),
        migrations.AlterModelOptions(
            name='workorder',
            options={'verbose_name': 'Work Order', 'verbose_name_plural': 'Work Orders'},
        ),
    ]
