# Generated by Django 5.0.2 on 2024-02-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0017_itemsumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemsumber',
            old_name='sku',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='itemsumber',
            name='jenis_sumber',
            field=models.CharField(choices=[('online', 'Online Store'), ('pabrik', 'Pabrik')], max_length=30),
        ),
    ]
