# Generated by Django 5.0.3 on 2024-03-26 02:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0018_items_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='Tanggal',
            new_name='tanggal_input',
        ),
        migrations.AddField(
            model_name='items',
            name='tanggal_pemesanan',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
