# Generated by Django 5.0.2 on 2024-02-22 07:18

import page1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0018_rename_sku_itemsumber_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='supplier_id',
            new_name='supplier',
        ),
        migrations.RemoveField(
            model_name='items',
            name='sumber',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='nomor_PO',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='revenue_PO',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='tanggal_PO',
            field=models.DateField(blank=True, default=page1.models.default_date, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='tanggal_input_accurate',
            field=models.DateField(blank=True, default=page1.models.default_date, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='tanggal_pengiriman_barang',
            field=models.DateField(blank=True, default=page1.models.default_date, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='tanggal_pengiriman_invoice',
            field=models.DateField(blank=True, default=page1.models.default_date, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='tanggal_process',
            field=models.DateField(blank=True, default=page1.models.default_date, null=True),
        ),
    ]
