# Generated by Django 5.0.2 on 2024-02-22 07:30

import page1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0019_rename_supplier_id_purchaseorder_supplier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='workorder',
            name='nomor_PO',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='revenue_PO',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='tanggal_PO',
            field=models.DateField(blank=True, default=page1.models.default_date, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='tanggal_input_accurate',
            field=models.DateField(blank=True, default=page1.models.default_date, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='tanggal_pengiriman_barang',
            field=models.DateField(blank=True, default=page1.models.default_date, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='tanggal_pengiriman_invoice',
            field=models.DateField(blank=True, default=page1.models.default_date, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='tanggal_process',
            field=models.DateField(blank=True, default=page1.models.default_date, null=True),
        ),
    ]
