# Generated by Django 5.0.3 on 2024-03-26 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0019_rename_tanggal_items_tanggal_input_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='tanggal_input',
            new_name='Tanggal',
        ),
    ]
