# Generated by Django 4.2.10 on 2024-02-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0020_rename_customer_id_workorder_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('process', 'Process'), ('accurate', 'Accurate'), ('pengiriman', 'Pengiriman Barang'), ('invoice', 'Pengiriman Invoice')], max_length=30),
        ),
    ]
