# Generated by Django 5.0.3 on 2024-03-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0020_rename_tanggal_input_items_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeralamat',
            name='detail',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='supplieralamat',
            name='detail',
            field=models.CharField(max_length=500),
        ),
    ]
