# Generated by Django 5.0.3 on 2024-03-27 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0018_alter_category_options_alter_customeralamat_options_and_more'),
        ('page1', '0020_rename_tanggal_input_items_tanggal'),
    ]

    operations = [
    ]
