# Generated by Django 5.0.3 on 2024-03-27 05:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0021_alter_customeralamat_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='tanggal_pemesanan',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
