# Generated by Django 5.0.2 on 2024-02-23 07:34

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0021_items_price_currency_alter_items_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='IDR', max_digits=15),
        ),
        migrations.AlterField(
            model_name='items',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('IDR', 'Indonesian Rupiah (Rp.)'), ('USD', 'US Dollar ($)')], default='IDR', editable=False, max_length=3),
        ),
    ]
