# Generated by Django 4.2.10 on 2024-02-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0021_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('order', 'Order Created'), ('pending', 'Pending'), ('process', 'Process'), ('accurate', 'Accurate'), ('pengiriman', 'Pengiriman Barang'), ('invoice', 'Pengiriman Invoice')], max_length=30),
        ),
    ]
