# Generated by Django 4.2.10 on 2024-03-27 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0021_merge_20240327_1219'),
        ('page1', '0022_alter_items_tanggal_pemesanan'),
    ]

    operations = [
    ]
