# Generated by Django 5.0.2 on 2024-02-23 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0022_alter_items_price_alter_items_price_currency'),
        ('page1', '0022_alter_purchaseorder_status'),
    ]

    operations = [
    ]
