# Generated by Django 5.0.3 on 2024-03-28 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0023_merge_20240327_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeralamat',
            name='kecamatan',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customeralamat',
            name='kelurahan',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customeralamat',
            name='kota',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='deliveryaddresses',
            name='detail',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='deliveryaddresses',
            name='kecamatan',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='deliveryaddresses',
            name='kelurahan',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='deliveryaddresses',
            name='kota',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='supplieralamat',
            name='kecamatan',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='supplieralamat',
            name='kelurahan',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='supplieralamat',
            name='kota',
            field=models.CharField(max_length=255),
        ),
    ]
