# Generated by Django 4.2.10 on 2024-03-28 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0023_merge_20240327_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Kecamatan',
                'verbose_name_plural': 'Kecamatan',
            },
        ),
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Provinsi',
                'verbose_name_plural': 'Provinsi',
            },
        ),
        migrations.AlterField(
            model_name='deliveryaddresses',
            name='detail',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='Kota',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('provinsi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page1.provinsi')),
            ],
            options={
                'verbose_name': 'Kota/Kabupaten',
                'verbose_name_plural': 'Kota/Kabupaten',
            },
        ),
        migrations.CreateModel(
            name='Kelurahan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('kecamatan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page1.kecamatan')),
            ],
            options={
                'verbose_name': 'Kelurahan/Desa',
                'verbose_name_plural': 'Kelurahan/Desa',
            },
        ),
        migrations.AddField(
            model_name='kecamatan',
            name='kota_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page1.kota'),
        ),
        migrations.AlterField(
            model_name='deliveryaddresses',
            name='kecamatan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page1.kecamatan'),
        ),
        migrations.AlterField(
            model_name='deliveryaddresses',
            name='kelurahan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page1.kelurahan'),
        ),
        migrations.AlterField(
            model_name='deliveryaddresses',
            name='kota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page1.kota'),
        ),
        migrations.AlterField(
            model_name='deliveryaddresses',
            name='provinsi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page1.provinsi'),
        ),
    ]
