# Generated by Django 5.0.3 on 2024-03-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0024_alter_customeralamat_kecamatan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='keterangan',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
