# Generated by Django 5.0.2 on 2024-02-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0025_alter_purchaseorder_status_alter_workorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.CharField(choices=[('ATK', 'Alat Tulis Kantor'), ('ELK', 'Elektronik Supplies'), ('FAS', 'Fashion'), ('ITS', 'IT Supplies'), ('KES', 'Kesehatan'), ('LPU', 'Lampu'), ('MAK', 'Makanan'), ('MGF', 'Management Fee'), ('MIN', 'Minuman'), ('MRO', 'Maintenance, Repair, and Operations'), ('OTO', 'Otomotif'), ('PER', 'Peralatan'), ('PRK', 'Perawatan dan Kecantikan'), ('PRT', 'Peralatan Rumah Tangga'), ('RTL', 'Rental'), ('SFT', 'Safety'), ('STG', 'Storage'), ('TVL', 'Travel'), ('UMM', 'Umum')], max_length=255),
        ),
    ]
