# Generated by Django 5.0.2 on 2024-02-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0026_alter_items_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='SKU',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
