from django.contrib import admin
from .models import *

admin.site.register(Customer)
admin.site.register(Supplier)
admin.site.register(CustomerPIC)
admin.site.register(SupplierPIC)
admin.site.register(CustomerAlamat)
admin.site.register(SupplierAlamat)
admin.site.register(Items)
admin.site.register(Category)
admin.site.register(ItemSumber)
admin.site.register(PurchaseOrder)
admin.site.register(WorkOrder)
admin.site.register(UserActionLog)
admin.site.register(Messenger)
admin.site.register(Vehicle)
admin.site.register(DeliveryAddresses)
admin.site.register(Events)
admin.site.register(LogBook)