# Generated by Django 4.2.10 on 2024-03-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plat', models.CharField(max_length=20)),
                ('DO', models.PositiveIntegerField()),
                ('no_Tiket', models.CharField(max_length=15)),
                ('berat', models.PositiveIntegerField()),
                ('tanggal', models.DateField()),
                ('reject', models.IntegerField()),
            ],
        ),
    ]
