# Generated by Django 5.0.4 on 2024-05-20 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kayu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('detail', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Kayu',
                'verbose_name_plural': 'Jenis Kayu',
            },
        ),
        migrations.CreateModel(
            name='Lokasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('detail', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Lokasi Potong',
                'verbose_name_plural': 'Lokasi Potong',
            },
        ),
        migrations.CreateModel(
            name='Tujuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('detail', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Pabrik Tujuan',
                'verbose_name_plural': 'Pabrik Tujuan',
            },
        ),
        migrations.CreateModel(
            name='Group_Kayu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('kayu', models.ManyToManyField(to='lik.kayu')),
            ],
            options={
                'verbose_name': 'Kayu Group Access',
                'verbose_name_plural': 'Kayu Group Access',
            },
        ),
        migrations.CreateModel(
            name='Group_Lokasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('lokasi', models.ManyToManyField(to='lik.lokasi')),
            ],
            options={
                'verbose_name': 'Lokasi Group Access',
                'verbose_name_plural': 'Lokasi Group Access',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiketId', models.CharField(blank=True, max_length=100, null=True)),
                ('plat', models.CharField(max_length=20, null=True)),
                ('driver', models.CharField(max_length=30, null=True)),
                ('PO', models.CharField(max_length=40, null=True)),
                ('DO', models.CharField(max_length=7, null=True)),
                ('lokasi', models.CharField(max_length=255, null=True)),
                ('tujuan', models.CharField(max_length=255, null=True)),
                ('kayu', models.CharField(max_length=255, null=True)),
                ('no_tiket', models.CharField(max_length=15, null=True)),
                ('berat', models.PositiveIntegerField(null=True)),
                ('tanggal', models.DateField(null=True)),
                ('reject', models.PositiveIntegerField(null=True)),
                ('foto', models.ImageField(null=True, upload_to='report_photos/')),
                ('og_foto', models.ImageField(null=True, upload_to='report_photos/')),
                ('date_time', models.DateTimeField(null=True)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group_Tujuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('tujuan', models.ManyToManyField(to='lik.tujuan')),
            ],
            options={
                'verbose_name': 'Tujuan Group Access',
                'verbose_name_plural': 'Tujuan Group Access',
            },
        ),
    ]
