# Generated by Django 4.2.10 on 2024-03-22 06:35

from django.db import migrations
import django_measurement.models
import measurement.measures.mass


class Migration(migrations.Migration):

    dependencies = [
        ('lik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='berat',
            field=django_measurement.models.MeasurementField(measurement=measurement.measures.mass.Mass, null=True),
        ),
    ]
