# Generated by Django 4.2.10 on 2024-03-22 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lik', '0002_alter_report_berat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='no_Tiket',
            new_name='no_tiket',
        ),
    ]
