# Generated by Django 4.2.10 on 2024-03-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lik', '0003_rename_no_tiket_report_no_tiket'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='driver',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='berat',
            field=models.PositiveIntegerField(),
        ),
    ]
