# Generated by Django 4.2.10 on 2024-03-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lik', '0004_report_driver_alter_report_berat'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='PO',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
