# Generated by Django 4.2.10 on 2024-03-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lik', '0005_report_po'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='DO',
            field=models.IntegerField(),
        ),
    ]
