# Generated by Django 4.2.10 on 2024-03-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lik', '0006_alter_report_do'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='DO',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='reject',
            field=models.PositiveIntegerField(),
        ),
    ]
