# Generated by Django 5.0.3 on 2024-03-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lik', '0007_alter_report_do_alter_report_reject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='DO',
            field=models.CharField(max_length=7),
        ),
    ]
