# Generated by Django 5.0.3 on 2024-03-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lik', '0009_alter_report_plat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='DO',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='PO',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='berat',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='driver',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='no_tiket',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='reject',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='tanggal',
            field=models.DateField(null=True),
        ),
    ]
