# Generated by Django 5.0.3 on 2024-03-25 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lik', '0011_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
